name: pre-merge-build
run-name: pre merge build
on:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/pre-merge-build.yml'
jobs:
  execute-test-in-java17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: execute test
        run: mvn test
  execute-test-in-java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: execute test
        run: mvn test